"""add desc to url

Revision ID: 1836c43c86f0
Revises: 43be7ef5646c
Create Date: 2017-12-23 02:46:28.829535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1836c43c86f0'
down_revision = '43be7ef5646c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('desc', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'desc')
    # ### end Alembic commands ###
