"""create table url

Revision ID: 43be7ef5646c
Revises: 1b206398fe65
Create Date: 2017-12-22 01:34:34.188132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43be7ef5646c'
down_revision = '1b206398fe65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###
