"""add columns to url

Revision ID: f3ff66f44aca
Revises: 1836c43c86f0
Create Date: 2018-01-11 14:19:27.019484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ff66f44aca'
down_revision = '1836c43c86f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('code_url', sa.String(length=100), nullable=True))
    op.add_column('url', sa.Column('login_name', sa.String(length=100), nullable=True))
    op.add_column('url', sa.Column('login_password', sa.String(length=100), nullable=True))
    op.add_column('url', sa.Column('login_url', sa.String(length=100), nullable=True))
    op.add_column('url', sa.Column('real_login_url', sa.String(length=100), nullable=True))
    op.add_column('url', sa.Column('redis_host', sa.String(length=100), nullable=True))
    op.add_column('url', sa.Column('redis_password', sa.String(length=100), nullable=True))
    op.add_column('url', sa.Column('redis_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'redis_port')
    op.drop_column('url', 'redis_password')
    op.drop_column('url', 'redis_host')
    op.drop_column('url', 'real_login_url')
    op.drop_column('url', 'login_url')
    op.drop_column('url', 'login_password')
    op.drop_column('url', 'login_name')
    op.drop_column('url', 'code_url')
    # ### end Alembic commands ###
